### ISSUE TITLE
Process this list of issues

### ISSUE THREAD

**Issue by bmyerz** [sotl-technology/rubricapp#49]
In GitLab by @bmyerz on Nov 21, 2019, 15:48

From Brandon's third-party user testing

These are under this issue

* [ ]  Need to save file path on new rubric failed (not sure what this is anymore)
* [x] Evaluation description is a big centered text box
* [x] Grading page jumps to center page
* [x] Illuminate top tabs by where you are
* [x] Comment box on grading gets big
* [x] Get rid of go to top/bottom buttons
* [x] Comment goes away after submitting (related to #59 )
* [x] Last edit on grade page date not human readable
* [x] Do not underline chosen e.g. none and number chosen just do bold
* [x] New tab/add grade tab inconsistent
* [x] Breadcrumb on top of grading page feels like you want to click it
* [x] Evaluations should be first not create new evaluation tab
* [x] Attendance isn't saving and also confusing that it doesnt have it's own update button (related to #59 )
* [x] Manage from profile page turns it always to mobile mode
* [x] Share rubric is confusing edit vs overwrite (related to #59  )
* [x] Are emails working with rubric CS uiowa? (#55 )
* [x] Homepage isn't interactive. Maybe default to something else we already have? (#64 )
* [x] Maybe sure constraints on stuff like project name are told upfront
* [x] Update button being next to comment box makes it seem like it is for just the comment.
* [x] "Connect to project successfully" needs to be deleted 
* [x] on Mobile toolbox is overlapped by url bar at top on Samsung galaxy s7
* [x] Graphics on mobile tools are too cute and need to be informative
* [x] Mobile toolbox button slowly float up to be x is distracting. Same with desktop version. Too slow.
* [x] Grading criteria fold up button has small clickable space
* [x] grade page cancel button goes all the way back to Evals page.
* [x] Profile manage page says haven't graded and have graded. Seems confusing. See details button not do anything.

From 11/21 meeting with research group
* [x] most groups 4 or less people so optimize attendance display for that (avoid scroll)
* [x] "switch to" can avoid open/close each time to switch groups (related to breadcrumbs comment above)
* [x] highlight done groups in the grading page
* [x] setting for suggestions on/off in grading page (i.e., selectable advice)
* [x] improve PDF display feedback (changed this to html files, looks much better)
* [x] send a prioritized issues list back to the researchers

moved lower priority to #81

**Comment by bmyerz** [comment]
In GitLab by @bmyerz on Nov 21, 2019, 16:05

changed the description

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 5, 2019, 17:29

marked the task **"switch to" can avoid open/close each time to switch groups (related to breadcrumbs comment above)** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 5, 2019, 19:45

marked the task **most groups 4 or less people so optimize attendance display for that (avoid scroll)** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 5, 2019, 20:42

marked the task **highlight done groups in the grading page** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 5, 2019, 21:57

marked the task **Grading page jumps to center page** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 5, 2019, 22:00

marked the task **Breadcrumb on top of grading page feels like you want to click it** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 11, 2019, 11:23

marked the task **setting for suggestions on/off in grading page (i.e., selectable advice)** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 11, 2019, 11:23

marked the task **Get rid of go to top/bottom buttons** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 11, 2019, 11:49

marked the task **setting for suggestions on/off in grading page (i.e., selectable advice)** as incomplete

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 11, 2019, 11:50

marked the task **setting for suggestions on/off in grading page (i.e., selectable advice)** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 11, 2019, 13:03

marked the task **setting for suggestions on/off in grading page (i.e., selectable advice)** as incomplete

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 20, 2019, 13:09

marked the task **setting for suggestions on/off in grading page (i.e., selectable advice)** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 20, 2019, 13:32

marked the task **Comment box on grading gets big** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Dec 20, 2019, 13:32

marked the task **Evaluation description is a big centered text box** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 16:18

marked the task **Illuminate top tabs by where you are** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 16:40

marked the task **Last edit on grade page date not human readable** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 16:41

marked the task **Do not underline chosen e.g. none and number chosen just do bold** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 16:59

marked the task **New tab/add grade tab inconsistent** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 17:41

marked the task **Evaluations should be first not create new evaluation tab** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 17:45

marked the task **Manage from profile page turns it always to mobile mode** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 17:52

marked the task **Maybe sure constraints on stuff like project name are told upfront** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 18:13

marked the task **Update button being next to comment box makes it seem like it is for just the comment.** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 18:26

marked the task **on Mobile toolbox is overlapped by url bar at top on Samsung galaxy s7** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 18:27

marked the task **Graphics on mobile tools are too cute and need to be informative** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 18:27

marked the task **Mobile toolbox button slowly float up to be x is distracting. Same with desktop version. Too slow.** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 18:29

marked the task **Grading criteria fold up button has small clickable space** as completed

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 18:30

marked the task **Profile manage page says haven't graded and have graded. Seems confusing. See details button not do anything.** as completed
